// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package GenTableColumnModel

import (
	"github.com/gogf/gf/frame/g"
)

var (
	// Table is the table name of goods.
	Table = "gen_table_column"
	M     = g.DB("default").Model(Table).Safe()
)

// ResEntity is the golang structure for table gen_table_column.
type ResEntity struct {
	ColumnName      string        `orm:"columnName"       json:"columnName"`               // 列名称 小驼峰
	ColumnComment   string        `orm:"columnComment"    json:"columnComment"`            // 列描述
	ColumnType      string        `orm:"columnType"       json:"columnType"`               // 列类型  数据库的类型
	ColumnLabel     string        `orm:"columnLabel"      json:"columnLabel"`              //字段label,如状态#1:开启,2:关闭； ColumnLabel就会是"状态"
	IsDictColumn    string        `orm:"isDictParams"     json:"isDictParams" default:"0"` // 是否字典字段（1是 0不是）
	IsPicColumn     string        `orm:"isPicColumn"      json:"isPicColumn" default:"0"`  // 是否图片字段（1是 0不是）
	ColumnLabelDict []*DictEntity //ColumnLabelDict就会是 {label:"开启",value:1}
	GoType          string        `orm:"goType"           json:"goType"`                       // Go类型 float64 uint int uint64 int64 *gtime.Time string
	GoField         string        `orm:"goField"          json:"goField"`                      // Go字段名 大驼峰
	HtmlField       string        `orm:"htmlField"        json:"htmlField"`                    // html字段名 小驼峰
	HtmlType        string        `orm:"htmlType"         json:"htmlType"`                     // 显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）input\datetime\textarea\cl-upload-space-preview\
	IsCuParams      string        `orm:"isCuParams"       json:"isCuParams" default:"0"`       // 是否新增、更新参数（1是 0不是）
	IsKeyWordParams string        `orm:"isKeyWordParams"   json:"isKeyWordParams" default:"0"` // 是否关键字-用户分页模糊查询请求参数（1是 0不是）
	IsSearchParams  string        `orm:"isSearchParams"   json:"isSearchParams" default:"0"`   // 是否查询请求参数（1是 0不是）
	IsPk            string        `orm:"isPk"             json:"isPk"  default:"0"`            // 是否主键（1是）
	IsIncrement     string        `orm:"isIncrement"      json:"isIncrement"  default:"0"`     // 是否自增（1是）
	IsRequired      string        `orm:"isRequired"       json:"isRequired" default:"0"`       // 是否必填（1是）
	Sort            int           `orm:"sort"             json:"sort" default:"0"`             // 排序

}

type DictEntity struct {
	Label string `orm:"label"       json:"label"`
	Value string `orm:"value"       json:"value"`
}
